services:
  # 1. Base de datos
  db:
    image: mysql:8.0
    container_name: tourfer-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tourfer_data
      MYSQL_USER: admin
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
# El "0_" asegura que Docker cree las tablas PRIMERO
      - ./setup_database.sql:/docker-entrypoint-initdb.d/0_setup.sql
      # El "1_" y "2_" insertan los datos DESPUÉS
      - ./API_Tours/seed.sql:/docker-entrypoint-initdb.d/1_tours.sql
      - ./API_Bookings/seed.sql:/docker-entrypoint-initdb.d/2_bookings.sql
    networks:
      - tourfer_net
    # PRO-TIP: Le preguntamos a MySQL cada 5 segundos si ya está listo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 10

  # 2. Servicio de Catálogo
  catalogo:
    build: ./API_Tours
    container_name: tourfer-catalogo
    ports:
      - "5001:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password123
      - MYSQL_DB=tourfer_data
      - MYSQL_PORT=3306
    depends_on:
      db:
        # La API espera a que el healthcheck de la DB esté en verde
        condition: service_healthy
    networks:
      - tourfer_net

  # 3. Servicio de Reservas
  reservas:
    build: ./API_Bookings
    container_name: tourfer-reservas
    ports:
      - "5002:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password123
      - MYSQL_DB=tourfer_data
      - MYSQL_PORT=3306
      - CATALOGO_API_URL=http://tourfer-catalogo:5000
      - MYSQL_SSL_CA=
    depends_on:
      db:
        # La API espera a que el healthcheck de la DB esté en verde
        condition: service_healthy
    networks:
      - tourfer_net

networks:
  tourfer_net:
    driver: bridge