services:
  backend:
    build: ./backend
    ports:
      - "5002:5000"
    depends_on:
      - db
    env_file:
      - .env
    restart: always
  db:
    image: mysql:8.4
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
  usuarios:
    build: ./usuarios
    ports:
      - "5001:5000"
    restart: always
  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - backend
      - usuarios
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  db_data: