FROM python:3.11-slim

WORKDIR /app

# 1. Instalar dependencias del sistema operativo requeridas para mysqlclient
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       gcc \
       pkg-config \
       default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

# 2. Copiar requerimientos e instalarlos
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 3. Copiar el resto del código
COPY . .

EXPOSE 5000

CMD ["python", "app.py"]